name: Generate cat paw commits 🐾

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate cat-paw animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/cat-paws.svg?palette=github-light&color_snake=f7a1c4&color_dots=#cdeac0,#f7d6e0,#c1e1c1,#f4c2c2,#ffffff
            dist/cat-paws-dark.svg?palette=github-dark

      - name: push cat paws to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
